name: cron.scalebox
cluster: local

modules:
  filelist:
    base_image: hub.cstcloud.cn/scalebox/cron
    schedule_mode: HEAD
    parameters:
      start_message: ANY
    volumes:
      - ${PWD}/cron.txt:/cron.txt:ro
    sink_modules:
      - mod0
      - mod1

  mod0:
    base_image: hub.cstcloud.cn/scalebox/agent
  mod1:
    base_image: hub.cstcloud.cn/scalebox/agent
