name: app-primes-g${NUM_GROUPS}-p${NUM_PARALLEL}
label: Prototype for Distributed Primes Calculation
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  message_router: mr-job

jobs:
  my-job:
    label: calc primes
    base_image: app-primes/calc
    hosts:
      - ${CALC_HOST}:${NUM_PARALLEL}
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      batch_message_size: 2
    environments:
      - LENGTH=${GROUP_SIZE}

  mr-job:
    label: Summary of results
    base_image: hub.cstcloud.cn/scalebox/agent
    arguments:
      code_path: ${PWD}/mr-code
      sleep_seconds: 10
      max_sleep_count: 100
      slot_options: slot_on_head
      bulk_message_size: ${BULK_MESSAGE_SIZE}
      # slot_options: reserved_on_exit
    parameters:
      start_message: ANY
    environments:
      - NUM_GROUPS=${NUM_GROUPS}
      - GROUP_SIZE=${GROUP_SIZE}
      - TASK_DIST_MODE=${TASK_DIST_MODE}
