name: check_test.feature
cluster: ${CLUSTER}

modules:
  check_test:
    base_image: hub.cstcloud.cn/scalebox/agent:latest
    parameters:
      slot_on_head: yes
      start_task: ANY
    arguments:
      code_path: ${PWD}/code
      dir_quota_gb: ${DIR_QUOTA_GB}
      space_free_gb: ${SPACE_FREE_GB}
    environments:
      - ACTION_CHECK=${ACTION_CHECK}
