name: vtask_size.test
cluster: ${CLUSTER}

modules:
  vtask-size:
    base_image: hub.cstcloud.cn/scalebox/agent
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      vtask_size: 2
    slots: 
      - '${HOSTS}'
  