name: timeout-gen.test-app
cluster: local

modules:
  timeout-gen:
    base_image: timeout-gen
    parameters:
      start_task: 0
    arguments:
      task_max_seconds:	10
      slot_options: slot_on_head
    environments:
      - SLEEP_SECONDS=20
