name: side-car.test-app
cluster: local

modules:
  side_car_test:
    base_image: hub.cstcloud.cn/scalebox/agent
    arguments:
      code_path: ${PWD}/code
      slot_options: slot_on_head
      # 3 minutes
      max_idle_polls: 50
    parameters:
      start_task: 0
    environments:
      - ACTION_RUN=${ACTION_RUN}
      - ACTION_SETUP=${ACTION_SETUP}
      - ACTION_TEARDOWN=${ACTION_TEARDOWN}
      - ACTION_CHECK=${ACTION_CHECK}
