name: vtask.examples
cluster: ${CLUSTER}
parameters:
  message_router: message-router

modules:
  wait-queue:
    base_image: hub.cstcloud.cn/scalebox/agent:latest
    arguments:
      code_path: ${PWD}/modules/wait-queue/code
      slot_options: slot_on_head
    parameters:
      # 避免提早分配资源，使得vtask在wait-queue中
      vtask_size: 1
    environments:
      - TASK_DIST_MODE=${TASK_DIST_MODE}

  vtask-head:
    base_image: hub.cstcloud.cn/scalebox/agent:latest
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      vtask_role: head
      vtask_size: 2
      vtask_size_sema_copy: yes
    slots: 
      - ${HEAD_SLOTS}

  vtask-core:
    base_image: hub.cstcloud.cn/scalebox/agent:latest
    arguments:
      code_path: ${PWD}/modules/vtask-core/code
    parameters:
      task_dist_mode: ${CORE_MODE}
      vtask_role: core
    environments:
      - RUNNING_SECONDS=${RUNNING_SECONDS}
    slots:
      - ${CORE_SLOTS}

  vtask-tail:
    base_image: hub.cstcloud.cn/scalebox/agent:latest
    arguments:
      slot_options: slot_on_head
    parameters:
      vtask_role: tail

  message-router:
    base_image: hub.cstcloud.cn/scalebox/agent:latest
    arguments:
      code_path: ${PWD}/mr-code
      slot_options: slot_on_head
    environments:
      - TASK_DIST_MODE=${TASK_DIST_MODE}
