name: vtask.examples
cluster: ${CLUSTER}
parameters:
  main_router: main-router

modules:
  wait-queue:
    arguments:
      # code_path: ${PWD}/modules/wait-queue/code
      slot_options: slot_on_head
    parameters:
      # 避免提早分配资源，使得vtask在wait-queue中
      vtask_size: 1

  vtask-head:
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      vtask_role: head
      vtask_size: 2
      vtask_size_sema_copy: yes
    slots: 
      - ${HEAD_SLOTS}

  vtask-core:
    arguments:
      code_path: ${PWD}/vtask-core
    parameters:
      task_dist_mode: ${CORE_MODE}
      vtask_role: core
    environments:
      - RUNNING_SECONDS=${RUNNING_SECONDS}
    slots:
      - ${CORE_SLOTS}

  vtask-tail:
    arguments:
      slot_options: slot_on_head
    parameters:
      vtask_role: tail

  main-router:
    arguments:
      code_path: ${PWD}/main-router
      slot_options: slot_on_head
    environments:
      - TASK_DIST_MODE=${TASK_DIST_MODE}
