// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: app.proto

package scalebox

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppServiceClient is the client API for AppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppServiceClient interface {
	ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
	GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error)
	CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error)
	DeleteApp(ctx context.Context, in *DeleteAppRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetAppStatus(ctx context.Context, in *SetAppStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetAppFinished(ctx context.Context, in *SetAppFinishedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AppAddSlots(ctx context.Context, in *AppAddSlotsRequest, opts ...grpc.CallOption) (*AppAddSlotsResponse, error)
	GetAppRouter(ctx context.Context, in *GetAppRouterRequest, opts ...grpc.CallOption) (*GetAppRouterResponse, error)
	GetAppDAG(ctx context.Context, in *GetAppDAGRequest, opts ...grpc.CallOption) (*GetAppDAGResponse, error)
	ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error)
	GetModule(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*GetModuleResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	GetTaskHeader(ctx context.Context, in *GetTaskHeaderRequest, opts ...grpc.CallOption) (*GetTaskHeaderResponse, error)
	SetTaskHeader(ctx context.Context, in *SetTaskHeaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveTaskHeader(ctx context.Context, in *RemoveTaskHeaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RegisterRemoteAppLink(ctx context.Context, in *RegisterRemoteAppLinkRequest, opts ...grpc.CallOption) (*RegisterRemoteAppLinkResponse, error)
	GetVtaskVariable(ctx context.Context, in *GetVtaskVariableRequest, opts ...grpc.CallOption) (*GetVtaskVariableResponse, error)
	SetVtaskVariable(ctx context.Context, in *SetVtaskVariableRequest, opts ...grpc.CallOption) (*SetVtaskVariableResponse, error)
	GetVtaskSemaphore(ctx context.Context, in *GetVtaskSemaphoreRequest, opts ...grpc.CallOption) (*GetVtaskSemaphoreResponse, error)
	CreateVtaskSemaphore(ctx context.Context, in *CreateVtaskSemaphoreRequest, opts ...grpc.CallOption) (*CreateVtaskSemaphoreResponse, error)
	AddVtaskSemaphore(ctx context.Context, in *AddVtaskSemaphoreRequest, opts ...grpc.CallOption) (*AddVtaskSemaphoreResponse, error)
	DeleteVtaskSemaphore(ctx context.Context, in *DeleteVtaskSemaphoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListVTasks(ctx context.Context, in *ListVTasksRequest, opts ...grpc.CallOption) (*ListVTasksResponse, error)
	ListVTaskSubtasks(ctx context.Context, in *ListVTaskSubtasksRequest, opts ...grpc.CallOption) (*ListVTasksResponse, error)
	// VTask 高级操作
	BindVtaskResource(ctx context.Context, in *BindVtaskResourceRequest, opts ...grpc.CallOption) (*BindVtaskResourceResponse, error)
	UnbindVtaskResource(ctx context.Context, in *UnbindVtaskResourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddVtaskSubtask(ctx context.Context, in *AddVtaskSubtaskRequest, opts ...grpc.CallOption) (*AddVtaskSubtaskResponse, error)
	GetVtask(ctx context.Context, in *GetVtaskRequest, opts ...grpc.CallOption) (*GetVtaskResponse, error)
	FailVtask(ctx context.Context, in *FailVtaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type appServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppServiceClient(cc grpc.ClientConnInterface) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	out := new(ListAppsResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/ListApps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error) {
	out := new(GetAppResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error) {
	out := new(CreateAppResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/CreateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DeleteApp(ctx context.Context, in *DeleteAppRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/DeleteApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) SetAppStatus(ctx context.Context, in *SetAppStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/SetAppStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) SetAppFinished(ctx context.Context, in *SetAppFinishedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/SetAppFinished", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AppAddSlots(ctx context.Context, in *AppAddSlotsRequest, opts ...grpc.CallOption) (*AppAddSlotsResponse, error) {
	out := new(AppAddSlotsResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/AppAddSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppRouter(ctx context.Context, in *GetAppRouterRequest, opts ...grpc.CallOption) (*GetAppRouterResponse, error) {
	out := new(GetAppRouterResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetAppRouter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetAppDAG(ctx context.Context, in *GetAppDAGRequest, opts ...grpc.CallOption) (*GetAppDAGResponse, error) {
	out := new(GetAppDAGResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetAppDAG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error) {
	out := new(ListModulesResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/ListModules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetModule(ctx context.Context, in *GetModuleRequest, opts ...grpc.CallOption) (*GetModuleResponse, error) {
	out := new(GetModuleResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetModule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetTaskHeader(ctx context.Context, in *GetTaskHeaderRequest, opts ...grpc.CallOption) (*GetTaskHeaderResponse, error) {
	out := new(GetTaskHeaderResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetTaskHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) SetTaskHeader(ctx context.Context, in *SetTaskHeaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/SetTaskHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) RemoveTaskHeader(ctx context.Context, in *RemoveTaskHeaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/RemoveTaskHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) RegisterRemoteAppLink(ctx context.Context, in *RegisterRemoteAppLinkRequest, opts ...grpc.CallOption) (*RegisterRemoteAppLinkResponse, error) {
	out := new(RegisterRemoteAppLinkResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/RegisterRemoteAppLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetVtaskVariable(ctx context.Context, in *GetVtaskVariableRequest, opts ...grpc.CallOption) (*GetVtaskVariableResponse, error) {
	out := new(GetVtaskVariableResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetVtaskVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) SetVtaskVariable(ctx context.Context, in *SetVtaskVariableRequest, opts ...grpc.CallOption) (*SetVtaskVariableResponse, error) {
	out := new(SetVtaskVariableResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/SetVtaskVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetVtaskSemaphore(ctx context.Context, in *GetVtaskSemaphoreRequest, opts ...grpc.CallOption) (*GetVtaskSemaphoreResponse, error) {
	out := new(GetVtaskSemaphoreResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetVtaskSemaphore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) CreateVtaskSemaphore(ctx context.Context, in *CreateVtaskSemaphoreRequest, opts ...grpc.CallOption) (*CreateVtaskSemaphoreResponse, error) {
	out := new(CreateVtaskSemaphoreResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/CreateVtaskSemaphore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AddVtaskSemaphore(ctx context.Context, in *AddVtaskSemaphoreRequest, opts ...grpc.CallOption) (*AddVtaskSemaphoreResponse, error) {
	out := new(AddVtaskSemaphoreResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/AddVtaskSemaphore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DeleteVtaskSemaphore(ctx context.Context, in *DeleteVtaskSemaphoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/DeleteVtaskSemaphore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ListVTasks(ctx context.Context, in *ListVTasksRequest, opts ...grpc.CallOption) (*ListVTasksResponse, error) {
	out := new(ListVTasksResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/ListVTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) ListVTaskSubtasks(ctx context.Context, in *ListVTaskSubtasksRequest, opts ...grpc.CallOption) (*ListVTasksResponse, error) {
	out := new(ListVTasksResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/ListVTaskSubtasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) BindVtaskResource(ctx context.Context, in *BindVtaskResourceRequest, opts ...grpc.CallOption) (*BindVtaskResourceResponse, error) {
	out := new(BindVtaskResourceResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/BindVtaskResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) UnbindVtaskResource(ctx context.Context, in *UnbindVtaskResourceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/UnbindVtaskResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) AddVtaskSubtask(ctx context.Context, in *AddVtaskSubtaskRequest, opts ...grpc.CallOption) (*AddVtaskSubtaskResponse, error) {
	out := new(AddVtaskSubtaskResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/AddVtaskSubtask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetVtask(ctx context.Context, in *GetVtaskRequest, opts ...grpc.CallOption) (*GetVtaskResponse, error) {
	out := new(GetVtaskResponse)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/GetVtask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) FailVtask(ctx context.Context, in *FailVtaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.AppService/FailVtask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServiceServer is the server API for AppService service.
// All implementations should embed UnimplementedAppServiceServer
// for forward compatibility
type AppServiceServer interface {
	ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error)
	GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error)
	CreateApp(context.Context, *CreateAppRequest) (*CreateAppResponse, error)
	DeleteApp(context.Context, *DeleteAppRequest) (*emptypb.Empty, error)
	SetAppStatus(context.Context, *SetAppStatusRequest) (*emptypb.Empty, error)
	SetAppFinished(context.Context, *SetAppFinishedRequest) (*emptypb.Empty, error)
	AppAddSlots(context.Context, *AppAddSlotsRequest) (*AppAddSlotsResponse, error)
	GetAppRouter(context.Context, *GetAppRouterRequest) (*GetAppRouterResponse, error)
	GetAppDAG(context.Context, *GetAppDAGRequest) (*GetAppDAGResponse, error)
	ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error)
	GetModule(context.Context, *GetModuleRequest) (*GetModuleResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	GetTaskHeader(context.Context, *GetTaskHeaderRequest) (*GetTaskHeaderResponse, error)
	SetTaskHeader(context.Context, *SetTaskHeaderRequest) (*emptypb.Empty, error)
	RemoveTaskHeader(context.Context, *RemoveTaskHeaderRequest) (*emptypb.Empty, error)
	RegisterRemoteAppLink(context.Context, *RegisterRemoteAppLinkRequest) (*RegisterRemoteAppLinkResponse, error)
	GetVtaskVariable(context.Context, *GetVtaskVariableRequest) (*GetVtaskVariableResponse, error)
	SetVtaskVariable(context.Context, *SetVtaskVariableRequest) (*SetVtaskVariableResponse, error)
	GetVtaskSemaphore(context.Context, *GetVtaskSemaphoreRequest) (*GetVtaskSemaphoreResponse, error)
	CreateVtaskSemaphore(context.Context, *CreateVtaskSemaphoreRequest) (*CreateVtaskSemaphoreResponse, error)
	AddVtaskSemaphore(context.Context, *AddVtaskSemaphoreRequest) (*AddVtaskSemaphoreResponse, error)
	DeleteVtaskSemaphore(context.Context, *DeleteVtaskSemaphoreRequest) (*emptypb.Empty, error)
	ListVTasks(context.Context, *ListVTasksRequest) (*ListVTasksResponse, error)
	ListVTaskSubtasks(context.Context, *ListVTaskSubtasksRequest) (*ListVTasksResponse, error)
	// VTask 高级操作
	BindVtaskResource(context.Context, *BindVtaskResourceRequest) (*BindVtaskResourceResponse, error)
	UnbindVtaskResource(context.Context, *UnbindVtaskResourceRequest) (*emptypb.Empty, error)
	AddVtaskSubtask(context.Context, *AddVtaskSubtaskRequest) (*AddVtaskSubtaskResponse, error)
	GetVtask(context.Context, *GetVtaskRequest) (*GetVtaskResponse, error)
	FailVtask(context.Context, *FailVtaskRequest) (*emptypb.Empty, error)
}

// UnimplementedAppServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAppServiceServer struct {
}

func (UnimplementedAppServiceServer) ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApps not implemented")
}
func (UnimplementedAppServiceServer) GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApp not implemented")
}
func (UnimplementedAppServiceServer) CreateApp(context.Context, *CreateAppRequest) (*CreateAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApp not implemented")
}
func (UnimplementedAppServiceServer) DeleteApp(context.Context, *DeleteAppRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApp not implemented")
}
func (UnimplementedAppServiceServer) SetAppStatus(context.Context, *SetAppStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAppStatus not implemented")
}
func (UnimplementedAppServiceServer) SetAppFinished(context.Context, *SetAppFinishedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAppFinished not implemented")
}
func (UnimplementedAppServiceServer) AppAddSlots(context.Context, *AppAddSlotsRequest) (*AppAddSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppAddSlots not implemented")
}
func (UnimplementedAppServiceServer) GetAppRouter(context.Context, *GetAppRouterRequest) (*GetAppRouterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppRouter not implemented")
}
func (UnimplementedAppServiceServer) GetAppDAG(context.Context, *GetAppDAGRequest) (*GetAppDAGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppDAG not implemented")
}
func (UnimplementedAppServiceServer) ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModules not implemented")
}
func (UnimplementedAppServiceServer) GetModule(context.Context, *GetModuleRequest) (*GetModuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModule not implemented")
}
func (UnimplementedAppServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedAppServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedAppServiceServer) GetTaskHeader(context.Context, *GetTaskHeaderRequest) (*GetTaskHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskHeader not implemented")
}
func (UnimplementedAppServiceServer) SetTaskHeader(context.Context, *SetTaskHeaderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTaskHeader not implemented")
}
func (UnimplementedAppServiceServer) RemoveTaskHeader(context.Context, *RemoveTaskHeaderRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTaskHeader not implemented")
}
func (UnimplementedAppServiceServer) RegisterRemoteAppLink(context.Context, *RegisterRemoteAppLinkRequest) (*RegisterRemoteAppLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterRemoteAppLink not implemented")
}
func (UnimplementedAppServiceServer) GetVtaskVariable(context.Context, *GetVtaskVariableRequest) (*GetVtaskVariableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVtaskVariable not implemented")
}
func (UnimplementedAppServiceServer) SetVtaskVariable(context.Context, *SetVtaskVariableRequest) (*SetVtaskVariableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVtaskVariable not implemented")
}
func (UnimplementedAppServiceServer) GetVtaskSemaphore(context.Context, *GetVtaskSemaphoreRequest) (*GetVtaskSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVtaskSemaphore not implemented")
}
func (UnimplementedAppServiceServer) CreateVtaskSemaphore(context.Context, *CreateVtaskSemaphoreRequest) (*CreateVtaskSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVtaskSemaphore not implemented")
}
func (UnimplementedAppServiceServer) AddVtaskSemaphore(context.Context, *AddVtaskSemaphoreRequest) (*AddVtaskSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVtaskSemaphore not implemented")
}
func (UnimplementedAppServiceServer) DeleteVtaskSemaphore(context.Context, *DeleteVtaskSemaphoreRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVtaskSemaphore not implemented")
}
func (UnimplementedAppServiceServer) ListVTasks(context.Context, *ListVTasksRequest) (*ListVTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVTasks not implemented")
}
func (UnimplementedAppServiceServer) ListVTaskSubtasks(context.Context, *ListVTaskSubtasksRequest) (*ListVTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVTaskSubtasks not implemented")
}
func (UnimplementedAppServiceServer) BindVtaskResource(context.Context, *BindVtaskResourceRequest) (*BindVtaskResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindVtaskResource not implemented")
}
func (UnimplementedAppServiceServer) UnbindVtaskResource(context.Context, *UnbindVtaskResourceRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindVtaskResource not implemented")
}
func (UnimplementedAppServiceServer) AddVtaskSubtask(context.Context, *AddVtaskSubtaskRequest) (*AddVtaskSubtaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVtaskSubtask not implemented")
}
func (UnimplementedAppServiceServer) GetVtask(context.Context, *GetVtaskRequest) (*GetVtaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVtask not implemented")
}
func (UnimplementedAppServiceServer) FailVtask(context.Context, *FailVtaskRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailVtask not implemented")
}

// UnsafeAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServiceServer will
// result in compilation errors.
type UnsafeAppServiceServer interface {
	mustEmbedUnimplementedAppServiceServer()
}

func RegisterAppServiceServer(s grpc.ServiceRegistrar, srv AppServiceServer) {
	s.RegisterService(&AppService_ServiceDesc, srv)
}

func _AppService_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/ListApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ListApps(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetApp(ctx, req.(*GetAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/CreateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).CreateApp(ctx, req.(*CreateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DeleteApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DeleteApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/DeleteApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DeleteApp(ctx, req.(*DeleteAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_SetAppStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAppStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).SetAppStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/SetAppStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).SetAppStatus(ctx, req.(*SetAppStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_SetAppFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAppFinishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).SetAppFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/SetAppFinished",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).SetAppFinished(ctx, req.(*SetAppFinishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AppAddSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppAddSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AppAddSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/AppAddSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AppAddSlots(ctx, req.(*AppAddSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppRouter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppRouterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppRouter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetAppRouter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppRouter(ctx, req.(*GetAppRouterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetAppDAG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppDAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetAppDAG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetAppDAG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetAppDAG(ctx, req.(*GetAppDAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/ListModules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ListModules(ctx, req.(*ListModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetModule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetModule(ctx, req.(*GetModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetTaskHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetTaskHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetTaskHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetTaskHeader(ctx, req.(*GetTaskHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_SetTaskHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTaskHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).SetTaskHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/SetTaskHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).SetTaskHeader(ctx, req.(*SetTaskHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_RemoveTaskHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTaskHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).RemoveTaskHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/RemoveTaskHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).RemoveTaskHeader(ctx, req.(*RemoveTaskHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_RegisterRemoteAppLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRemoteAppLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).RegisterRemoteAppLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/RegisterRemoteAppLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).RegisterRemoteAppLink(ctx, req.(*RegisterRemoteAppLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetVtaskVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVtaskVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetVtaskVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetVtaskVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetVtaskVariable(ctx, req.(*GetVtaskVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_SetVtaskVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVtaskVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).SetVtaskVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/SetVtaskVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).SetVtaskVariable(ctx, req.(*SetVtaskVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetVtaskSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVtaskSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetVtaskSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetVtaskSemaphore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetVtaskSemaphore(ctx, req.(*GetVtaskSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_CreateVtaskSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVtaskSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).CreateVtaskSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/CreateVtaskSemaphore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).CreateVtaskSemaphore(ctx, req.(*CreateVtaskSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AddVtaskSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVtaskSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AddVtaskSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/AddVtaskSemaphore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AddVtaskSemaphore(ctx, req.(*AddVtaskSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DeleteVtaskSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVtaskSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DeleteVtaskSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/DeleteVtaskSemaphore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DeleteVtaskSemaphore(ctx, req.(*DeleteVtaskSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ListVTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ListVTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/ListVTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ListVTasks(ctx, req.(*ListVTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_ListVTaskSubtasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVTaskSubtasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ListVTaskSubtasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/ListVTaskSubtasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ListVTaskSubtasks(ctx, req.(*ListVTaskSubtasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_BindVtaskResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindVtaskResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).BindVtaskResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/BindVtaskResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).BindVtaskResource(ctx, req.(*BindVtaskResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_UnbindVtaskResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindVtaskResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).UnbindVtaskResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/UnbindVtaskResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).UnbindVtaskResource(ctx, req.(*UnbindVtaskResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_AddVtaskSubtask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVtaskSubtaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).AddVtaskSubtask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/AddVtaskSubtask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).AddVtaskSubtask(ctx, req.(*AddVtaskSubtaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetVtask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVtaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetVtask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/GetVtask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetVtask(ctx, req.(*GetVtaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_FailVtask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailVtaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).FailVtask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.AppService/FailVtask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).FailVtask(ctx, req.(*FailVtaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppService_ServiceDesc is the grpc.ServiceDesc for AppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scalebox.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApps",
			Handler:    _AppService_ListApps_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _AppService_GetApp_Handler,
		},
		{
			MethodName: "CreateApp",
			Handler:    _AppService_CreateApp_Handler,
		},
		{
			MethodName: "DeleteApp",
			Handler:    _AppService_DeleteApp_Handler,
		},
		{
			MethodName: "SetAppStatus",
			Handler:    _AppService_SetAppStatus_Handler,
		},
		{
			MethodName: "SetAppFinished",
			Handler:    _AppService_SetAppFinished_Handler,
		},
		{
			MethodName: "AppAddSlots",
			Handler:    _AppService_AppAddSlots_Handler,
		},
		{
			MethodName: "GetAppRouter",
			Handler:    _AppService_GetAppRouter_Handler,
		},
		{
			MethodName: "GetAppDAG",
			Handler:    _AppService_GetAppDAG_Handler,
		},
		{
			MethodName: "ListModules",
			Handler:    _AppService_ListModules_Handler,
		},
		{
			MethodName: "GetModule",
			Handler:    _AppService_GetModule_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _AppService_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _AppService_GetTask_Handler,
		},
		{
			MethodName: "GetTaskHeader",
			Handler:    _AppService_GetTaskHeader_Handler,
		},
		{
			MethodName: "SetTaskHeader",
			Handler:    _AppService_SetTaskHeader_Handler,
		},
		{
			MethodName: "RemoveTaskHeader",
			Handler:    _AppService_RemoveTaskHeader_Handler,
		},
		{
			MethodName: "RegisterRemoteAppLink",
			Handler:    _AppService_RegisterRemoteAppLink_Handler,
		},
		{
			MethodName: "GetVtaskVariable",
			Handler:    _AppService_GetVtaskVariable_Handler,
		},
		{
			MethodName: "SetVtaskVariable",
			Handler:    _AppService_SetVtaskVariable_Handler,
		},
		{
			MethodName: "GetVtaskSemaphore",
			Handler:    _AppService_GetVtaskSemaphore_Handler,
		},
		{
			MethodName: "CreateVtaskSemaphore",
			Handler:    _AppService_CreateVtaskSemaphore_Handler,
		},
		{
			MethodName: "AddVtaskSemaphore",
			Handler:    _AppService_AddVtaskSemaphore_Handler,
		},
		{
			MethodName: "DeleteVtaskSemaphore",
			Handler:    _AppService_DeleteVtaskSemaphore_Handler,
		},
		{
			MethodName: "ListVTasks",
			Handler:    _AppService_ListVTasks_Handler,
		},
		{
			MethodName: "ListVTaskSubtasks",
			Handler:    _AppService_ListVTaskSubtasks_Handler,
		},
		{
			MethodName: "BindVtaskResource",
			Handler:    _AppService_BindVtaskResource_Handler,
		},
		{
			MethodName: "UnbindVtaskResource",
			Handler:    _AppService_UnbindVtaskResource_Handler,
		},
		{
			MethodName: "AddVtaskSubtask",
			Handler:    _AppService_AddVtaskSubtask_Handler,
		},
		{
			MethodName: "GetVtask",
			Handler:    _AppService_GetVtask_Handler,
		},
		{
			MethodName: "FailVtask",
			Handler:    _AppService_FailVtask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
