// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: coordination.proto

package scalebox

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoordinationServiceClient is the client API for CoordinationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinationServiceClient interface {
	GetSemaphore(ctx context.Context, in *GetSemaphoreRequest, opts ...grpc.CallOption) (*GetSemaphoreResponse, error)
	ListSemaphores(ctx context.Context, in *ListSemaphoresRequest, opts ...grpc.CallOption) (*ListSemaphoresResponse, error)
	CreateSemaphore(ctx context.Context, in *CreateSemaphoreRequest, opts ...grpc.CallOption) (*CreateSemaphoreResponse, error)
	UpdateSemaphore(ctx context.Context, in *UpdateSemaphoreRequest, opts ...grpc.CallOption) (*UpdateSemaphoreResponse, error)
	DeleteSemaphore(ctx context.Context, in *DeleteSemaphoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetVariable(ctx context.Context, in *GetVariableRequest, opts ...grpc.CallOption) (*GetVariableResponse, error)
	ListVariables(ctx context.Context, in *ListVariablesRequest, opts ...grpc.CallOption) (*ListVariablesResponse, error)
	SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*SetVariableResponse, error)
	DeleteVariable(ctx context.Context, in *DeleteVariableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetGlobal(ctx context.Context, in *GetGlobalRequest, opts ...grpc.CallOption) (*GetGlobalResponse, error)
	ListGlobals(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListGlobalsResponse, error)
	SetGlobal(ctx context.Context, in *SetGlobalRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteGlobal(ctx context.Context, in *DeleteGlobalRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Semagroup
	GetSemagroupMin(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupKeyValueResponse, error)
	GetSemagroupMax(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupKeyValueResponse, error)
	DiffSemagroupMin(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupDiffResponse, error)
	DiffSemagroupMax(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupDiffResponse, error)
	IncrementSemagroup(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupKeyValueResponse, error)
	DecrementSemagroup(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupKeyValueResponse, error)
}

type coordinationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationServiceClient(cc grpc.ClientConnInterface) CoordinationServiceClient {
	return &coordinationServiceClient{cc}
}

func (c *coordinationServiceClient) GetSemaphore(ctx context.Context, in *GetSemaphoreRequest, opts ...grpc.CallOption) (*GetSemaphoreResponse, error) {
	out := new(GetSemaphoreResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/GetSemaphore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) ListSemaphores(ctx context.Context, in *ListSemaphoresRequest, opts ...grpc.CallOption) (*ListSemaphoresResponse, error) {
	out := new(ListSemaphoresResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/ListSemaphores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) CreateSemaphore(ctx context.Context, in *CreateSemaphoreRequest, opts ...grpc.CallOption) (*CreateSemaphoreResponse, error) {
	out := new(CreateSemaphoreResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/CreateSemaphore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) UpdateSemaphore(ctx context.Context, in *UpdateSemaphoreRequest, opts ...grpc.CallOption) (*UpdateSemaphoreResponse, error) {
	out := new(UpdateSemaphoreResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/UpdateSemaphore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) DeleteSemaphore(ctx context.Context, in *DeleteSemaphoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/DeleteSemaphore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) GetVariable(ctx context.Context, in *GetVariableRequest, opts ...grpc.CallOption) (*GetVariableResponse, error) {
	out := new(GetVariableResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/GetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) ListVariables(ctx context.Context, in *ListVariablesRequest, opts ...grpc.CallOption) (*ListVariablesResponse, error) {
	out := new(ListVariablesResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/ListVariables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*SetVariableResponse, error) {
	out := new(SetVariableResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/SetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) DeleteVariable(ctx context.Context, in *DeleteVariableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/DeleteVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) GetGlobal(ctx context.Context, in *GetGlobalRequest, opts ...grpc.CallOption) (*GetGlobalResponse, error) {
	out := new(GetGlobalResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/GetGlobal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) ListGlobals(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListGlobalsResponse, error) {
	out := new(ListGlobalsResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/ListGlobals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) SetGlobal(ctx context.Context, in *SetGlobalRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/SetGlobal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) DeleteGlobal(ctx context.Context, in *DeleteGlobalRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/DeleteGlobal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) GetSemagroupMin(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupKeyValueResponse, error) {
	out := new(SemagroupKeyValueResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/GetSemagroupMin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) GetSemagroupMax(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupKeyValueResponse, error) {
	out := new(SemagroupKeyValueResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/GetSemagroupMax", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) DiffSemagroupMin(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupDiffResponse, error) {
	out := new(SemagroupDiffResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/DiffSemagroupMin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) DiffSemagroupMax(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupDiffResponse, error) {
	out := new(SemagroupDiffResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/DiffSemagroupMax", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) IncrementSemagroup(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupKeyValueResponse, error) {
	out := new(SemagroupKeyValueResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/IncrementSemagroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationServiceClient) DecrementSemagroup(ctx context.Context, in *SemagroupRequest, opts ...grpc.CallOption) (*SemagroupKeyValueResponse, error) {
	out := new(SemagroupKeyValueResponse)
	err := c.cc.Invoke(ctx, "/scalebox.CoordinationService/DecrementSemagroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinationServiceServer is the server API for CoordinationService service.
// All implementations should embed UnimplementedCoordinationServiceServer
// for forward compatibility
type CoordinationServiceServer interface {
	GetSemaphore(context.Context, *GetSemaphoreRequest) (*GetSemaphoreResponse, error)
	ListSemaphores(context.Context, *ListSemaphoresRequest) (*ListSemaphoresResponse, error)
	CreateSemaphore(context.Context, *CreateSemaphoreRequest) (*CreateSemaphoreResponse, error)
	UpdateSemaphore(context.Context, *UpdateSemaphoreRequest) (*UpdateSemaphoreResponse, error)
	DeleteSemaphore(context.Context, *DeleteSemaphoreRequest) (*emptypb.Empty, error)
	GetVariable(context.Context, *GetVariableRequest) (*GetVariableResponse, error)
	ListVariables(context.Context, *ListVariablesRequest) (*ListVariablesResponse, error)
	SetVariable(context.Context, *SetVariableRequest) (*SetVariableResponse, error)
	DeleteVariable(context.Context, *DeleteVariableRequest) (*emptypb.Empty, error)
	GetGlobal(context.Context, *GetGlobalRequest) (*GetGlobalResponse, error)
	ListGlobals(context.Context, *emptypb.Empty) (*ListGlobalsResponse, error)
	SetGlobal(context.Context, *SetGlobalRequest) (*emptypb.Empty, error)
	DeleteGlobal(context.Context, *DeleteGlobalRequest) (*emptypb.Empty, error)
	// Semagroup
	GetSemagroupMin(context.Context, *SemagroupRequest) (*SemagroupKeyValueResponse, error)
	GetSemagroupMax(context.Context, *SemagroupRequest) (*SemagroupKeyValueResponse, error)
	DiffSemagroupMin(context.Context, *SemagroupRequest) (*SemagroupDiffResponse, error)
	DiffSemagroupMax(context.Context, *SemagroupRequest) (*SemagroupDiffResponse, error)
	IncrementSemagroup(context.Context, *SemagroupRequest) (*SemagroupKeyValueResponse, error)
	DecrementSemagroup(context.Context, *SemagroupRequest) (*SemagroupKeyValueResponse, error)
}

// UnimplementedCoordinationServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCoordinationServiceServer struct {
}

func (UnimplementedCoordinationServiceServer) GetSemaphore(context.Context, *GetSemaphoreRequest) (*GetSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSemaphore not implemented")
}
func (UnimplementedCoordinationServiceServer) ListSemaphores(context.Context, *ListSemaphoresRequest) (*ListSemaphoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSemaphores not implemented")
}
func (UnimplementedCoordinationServiceServer) CreateSemaphore(context.Context, *CreateSemaphoreRequest) (*CreateSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSemaphore not implemented")
}
func (UnimplementedCoordinationServiceServer) UpdateSemaphore(context.Context, *UpdateSemaphoreRequest) (*UpdateSemaphoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSemaphore not implemented")
}
func (UnimplementedCoordinationServiceServer) DeleteSemaphore(context.Context, *DeleteSemaphoreRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSemaphore not implemented")
}
func (UnimplementedCoordinationServiceServer) GetVariable(context.Context, *GetVariableRequest) (*GetVariableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVariable not implemented")
}
func (UnimplementedCoordinationServiceServer) ListVariables(context.Context, *ListVariablesRequest) (*ListVariablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVariables not implemented")
}
func (UnimplementedCoordinationServiceServer) SetVariable(context.Context, *SetVariableRequest) (*SetVariableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariable not implemented")
}
func (UnimplementedCoordinationServiceServer) DeleteVariable(context.Context, *DeleteVariableRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVariable not implemented")
}
func (UnimplementedCoordinationServiceServer) GetGlobal(context.Context, *GetGlobalRequest) (*GetGlobalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobal not implemented")
}
func (UnimplementedCoordinationServiceServer) ListGlobals(context.Context, *emptypb.Empty) (*ListGlobalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGlobals not implemented")
}
func (UnimplementedCoordinationServiceServer) SetGlobal(context.Context, *SetGlobalRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGlobal not implemented")
}
func (UnimplementedCoordinationServiceServer) DeleteGlobal(context.Context, *DeleteGlobalRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGlobal not implemented")
}
func (UnimplementedCoordinationServiceServer) GetSemagroupMin(context.Context, *SemagroupRequest) (*SemagroupKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSemagroupMin not implemented")
}
func (UnimplementedCoordinationServiceServer) GetSemagroupMax(context.Context, *SemagroupRequest) (*SemagroupKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSemagroupMax not implemented")
}
func (UnimplementedCoordinationServiceServer) DiffSemagroupMin(context.Context, *SemagroupRequest) (*SemagroupDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiffSemagroupMin not implemented")
}
func (UnimplementedCoordinationServiceServer) DiffSemagroupMax(context.Context, *SemagroupRequest) (*SemagroupDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiffSemagroupMax not implemented")
}
func (UnimplementedCoordinationServiceServer) IncrementSemagroup(context.Context, *SemagroupRequest) (*SemagroupKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementSemagroup not implemented")
}
func (UnimplementedCoordinationServiceServer) DecrementSemagroup(context.Context, *SemagroupRequest) (*SemagroupKeyValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrementSemagroup not implemented")
}

// UnsafeCoordinationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationServiceServer will
// result in compilation errors.
type UnsafeCoordinationServiceServer interface {
	mustEmbedUnimplementedCoordinationServiceServer()
}

func RegisterCoordinationServiceServer(s grpc.ServiceRegistrar, srv CoordinationServiceServer) {
	s.RegisterService(&CoordinationService_ServiceDesc, srv)
}

func _CoordinationService_GetSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).GetSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/GetSemaphore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).GetSemaphore(ctx, req.(*GetSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_ListSemaphores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSemaphoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).ListSemaphores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/ListSemaphores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).ListSemaphores(ctx, req.(*ListSemaphoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_CreateSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).CreateSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/CreateSemaphore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).CreateSemaphore(ctx, req.(*CreateSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_UpdateSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).UpdateSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/UpdateSemaphore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).UpdateSemaphore(ctx, req.(*UpdateSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_DeleteSemaphore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSemaphoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).DeleteSemaphore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/DeleteSemaphore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).DeleteSemaphore(ctx, req.(*DeleteSemaphoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_GetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).GetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/GetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).GetVariable(ctx, req.(*GetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_ListVariables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVariablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).ListVariables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/ListVariables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).ListVariables(ctx, req.(*ListVariablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/SetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).SetVariable(ctx, req.(*SetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_DeleteVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).DeleteVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/DeleteVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).DeleteVariable(ctx, req.(*DeleteVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_GetGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).GetGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/GetGlobal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).GetGlobal(ctx, req.(*GetGlobalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_ListGlobals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).ListGlobals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/ListGlobals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).ListGlobals(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_SetGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGlobalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).SetGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/SetGlobal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).SetGlobal(ctx, req.(*SetGlobalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_DeleteGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGlobalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).DeleteGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/DeleteGlobal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).DeleteGlobal(ctx, req.(*DeleteGlobalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_GetSemagroupMin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemagroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).GetSemagroupMin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/GetSemagroupMin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).GetSemagroupMin(ctx, req.(*SemagroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_GetSemagroupMax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemagroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).GetSemagroupMax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/GetSemagroupMax",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).GetSemagroupMax(ctx, req.(*SemagroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_DiffSemagroupMin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemagroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).DiffSemagroupMin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/DiffSemagroupMin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).DiffSemagroupMin(ctx, req.(*SemagroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_DiffSemagroupMax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemagroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).DiffSemagroupMax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/DiffSemagroupMax",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).DiffSemagroupMax(ctx, req.(*SemagroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_IncrementSemagroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemagroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).IncrementSemagroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/IncrementSemagroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).IncrementSemagroup(ctx, req.(*SemagroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationService_DecrementSemagroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemagroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServiceServer).DecrementSemagroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scalebox.CoordinationService/DecrementSemagroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServiceServer).DecrementSemagroup(ctx, req.(*SemagroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinationService_ServiceDesc is the grpc.ServiceDesc for CoordinationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scalebox.CoordinationService",
	HandlerType: (*CoordinationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSemaphore",
			Handler:    _CoordinationService_GetSemaphore_Handler,
		},
		{
			MethodName: "ListSemaphores",
			Handler:    _CoordinationService_ListSemaphores_Handler,
		},
		{
			MethodName: "CreateSemaphore",
			Handler:    _CoordinationService_CreateSemaphore_Handler,
		},
		{
			MethodName: "UpdateSemaphore",
			Handler:    _CoordinationService_UpdateSemaphore_Handler,
		},
		{
			MethodName: "DeleteSemaphore",
			Handler:    _CoordinationService_DeleteSemaphore_Handler,
		},
		{
			MethodName: "GetVariable",
			Handler:    _CoordinationService_GetVariable_Handler,
		},
		{
			MethodName: "ListVariables",
			Handler:    _CoordinationService_ListVariables_Handler,
		},
		{
			MethodName: "SetVariable",
			Handler:    _CoordinationService_SetVariable_Handler,
		},
		{
			MethodName: "DeleteVariable",
			Handler:    _CoordinationService_DeleteVariable_Handler,
		},
		{
			MethodName: "GetGlobal",
			Handler:    _CoordinationService_GetGlobal_Handler,
		},
		{
			MethodName: "ListGlobals",
			Handler:    _CoordinationService_ListGlobals_Handler,
		},
		{
			MethodName: "SetGlobal",
			Handler:    _CoordinationService_SetGlobal_Handler,
		},
		{
			MethodName: "DeleteGlobal",
			Handler:    _CoordinationService_DeleteGlobal_Handler,
		},
		{
			MethodName: "GetSemagroupMin",
			Handler:    _CoordinationService_GetSemagroupMin_Handler,
		},
		{
			MethodName: "GetSemagroupMax",
			Handler:    _CoordinationService_GetSemagroupMax_Handler,
		},
		{
			MethodName: "DiffSemagroupMin",
			Handler:    _CoordinationService_DiffSemagroupMin_Handler,
		},
		{
			MethodName: "DiffSemagroupMax",
			Handler:    _CoordinationService_DiffSemagroupMax_Handler,
		},
		{
			MethodName: "IncrementSemagroup",
			Handler:    _CoordinationService_IncrementSemagroup_Handler,
		},
		{
			MethodName: "DecrementSemagroup",
			Handler:    _CoordinationService_DecrementSemagroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordination.proto",
}
