// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: coordination.proto

package scalebox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSemaphoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetSemaphoreRequest) Reset() {
	*x = GetSemaphoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSemaphoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSemaphoreRequest) ProtoMessage() {}

func (x *GetSemaphoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSemaphoreRequest.ProtoReflect.Descriptor instead.
func (*GetSemaphoreRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{0}
}

func (x *GetSemaphoreRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetSemaphoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSemaphoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value  int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Value0 int32  `protobuf:"varint,3,opt,name=value0,proto3" json:"value0,omitempty"`
}

func (x *GetSemaphoreResponse) Reset() {
	*x = GetSemaphoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSemaphoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSemaphoreResponse) ProtoMessage() {}

func (x *GetSemaphoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSemaphoreResponse.ProtoReflect.Descriptor instead.
func (*GetSemaphoreResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{1}
}

func (x *GetSemaphoreResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSemaphoreResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetSemaphoreResponse) GetValue0() int32 {
	if x != nil {
		return x.Value0
	}
	return 0
}

type ListSemaphoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId    int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Prefix   string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	LeafOnly bool   `protobuf:"varint,3,opt,name=leaf_only,json=leafOnly,proto3" json:"leaf_only,omitempty"`
}

func (x *ListSemaphoresRequest) Reset() {
	*x = ListSemaphoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSemaphoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSemaphoresRequest) ProtoMessage() {}

func (x *ListSemaphoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSemaphoresRequest.ProtoReflect.Descriptor instead.
func (*ListSemaphoresRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{2}
}

func (x *ListSemaphoresRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ListSemaphoresRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListSemaphoresRequest) GetLeafOnly() bool {
	if x != nil {
		return x.LeafOnly
	}
	return false
}

type ListSemaphoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*ListSemaphoresResponse_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ListSemaphoresResponse) Reset() {
	*x = ListSemaphoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSemaphoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSemaphoresResponse) ProtoMessage() {}

func (x *ListSemaphoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSemaphoresResponse.ProtoReflect.Descriptor instead.
func (*ListSemaphoresResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{3}
}

func (x *ListSemaphoresResponse) GetNodes() []*ListSemaphoresResponse_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CreateSemaphoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId          int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value          int32  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	ConflictAction string `protobuf:"bytes,4,opt,name=conflict_action,json=conflictAction,proto3" json:"conflict_action,omitempty"`
}

func (x *CreateSemaphoreRequest) Reset() {
	*x = CreateSemaphoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSemaphoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSemaphoreRequest) ProtoMessage() {}

func (x *CreateSemaphoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSemaphoreRequest.ProtoReflect.Descriptor instead.
func (*CreateSemaphoreRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSemaphoreRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CreateSemaphoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSemaphoreRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateSemaphoreRequest) GetConflictAction() string {
	if x != nil {
		return x.ConflictAction
	}
	return ""
}

type CreateSemaphoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CreateSemaphoreResponse) Reset() {
	*x = CreateSemaphoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSemaphoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSemaphoreResponse) ProtoMessage() {}

func (x *CreateSemaphoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSemaphoreResponse.ProtoReflect.Descriptor instead.
func (*CreateSemaphoreResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSemaphoreResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSemaphoreResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateSemaphoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Delta int32  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *UpdateSemaphoreRequest) Reset() {
	*x = UpdateSemaphoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSemaphoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSemaphoreRequest) ProtoMessage() {}

func (x *UpdateSemaphoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSemaphoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateSemaphoreRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSemaphoreRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *UpdateSemaphoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSemaphoreRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type UpdateSemaphoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateSemaphoreResponse) Reset() {
	*x = UpdateSemaphoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSemaphoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSemaphoreResponse) ProtoMessage() {}

func (x *UpdateSemaphoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSemaphoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateSemaphoreResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSemaphoreResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSemaphoreResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DeleteSemaphoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteSemaphoreRequest) Reset() {
	*x = DeleteSemaphoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSemaphoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSemaphoreRequest) ProtoMessage() {}

func (x *DeleteSemaphoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSemaphoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteSemaphoreRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSemaphoreRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DeleteSemaphoreRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetVariableRequest) Reset() {
	*x = GetVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableRequest) ProtoMessage() {}

func (x *GetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableRequest.ProtoReflect.Descriptor instead.
func (*GetVariableRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{9}
}

func (x *GetVariableRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *GetVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVariableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetVariableResponse) Reset() {
	*x = GetVariableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVariableResponse) ProtoMessage() {}

func (x *GetVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVariableResponse.ProtoReflect.Descriptor instead.
func (*GetVariableResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{10}
}

func (x *GetVariableResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVariableResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListVariablesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId    int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Prefix   string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	LeafOnly bool   `protobuf:"varint,3,opt,name=leaf_only,json=leafOnly,proto3" json:"leaf_only,omitempty"`
}

func (x *ListVariablesRequest) Reset() {
	*x = ListVariablesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariablesRequest) ProtoMessage() {}

func (x *ListVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariablesRequest.ProtoReflect.Descriptor instead.
func (*ListVariablesRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{11}
}

func (x *ListVariablesRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ListVariablesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListVariablesRequest) GetLeafOnly() bool {
	if x != nil {
		return x.LeafOnly
	}
	return false
}

type ListVariablesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*ListVariablesResponse_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ListVariablesResponse) Reset() {
	*x = ListVariablesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariablesResponse) ProtoMessage() {}

func (x *ListVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariablesResponse.ProtoReflect.Descriptor instead.
func (*ListVariablesResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{12}
}

func (x *ListVariablesResponse) GetNodes() []*ListVariablesResponse_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SetVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetVariableRequest) Reset() {
	*x = SetVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableRequest) ProtoMessage() {}

func (x *SetVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableRequest.ProtoReflect.Descriptor instead.
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{13}
}

func (x *SetVariableRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *SetVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetVariableRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetVariableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetVariableResponse) Reset() {
	*x = SetVariableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVariableResponse) ProtoMessage() {}

func (x *SetVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVariableResponse.ProtoReflect.Descriptor instead.
func (*SetVariableResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{14}
}

func (x *SetVariableResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetVariableResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteVariableRequest) Reset() {
	*x = DeleteVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVariableRequest) ProtoMessage() {}

func (x *DeleteVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVariableRequest.ProtoReflect.Descriptor instead.
func (*DeleteVariableRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteVariableRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *DeleteVariableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGlobalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetGlobalRequest) Reset() {
	*x = GetGlobalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGlobalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalRequest) ProtoMessage() {}

func (x *GetGlobalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{16}
}

func (x *GetGlobalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetGlobalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetGlobalResponse) Reset() {
	*x = GetGlobalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGlobalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalResponse) ProtoMessage() {}

func (x *GetGlobalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{17}
}

func (x *GetGlobalResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGlobalResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	T     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=t,proto3" json:"t,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{18}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KeyValue) GetT() *timestamppb.Timestamp {
	if x != nil {
		return x.T
	}
	return nil
}

type ListGlobalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Globals []*KeyValue `protobuf:"bytes,1,rep,name=globals,proto3" json:"globals,omitempty"`
}

func (x *ListGlobalsResponse) Reset() {
	*x = ListGlobalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGlobalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalsResponse) ProtoMessage() {}

func (x *ListGlobalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalsResponse.ProtoReflect.Descriptor instead.
func (*ListGlobalsResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{19}
}

func (x *ListGlobalsResponse) GetGlobals() []*KeyValue {
	if x != nil {
		return x.Globals
	}
	return nil
}

type SetGlobalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetGlobalRequest) Reset() {
	*x = SetGlobalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetGlobalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalRequest) ProtoMessage() {}

func (x *SetGlobalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalRequest.ProtoReflect.Descriptor instead.
func (*SetGlobalRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{20}
}

func (x *SetGlobalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetGlobalRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteGlobalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteGlobalRequest) Reset() {
	*x = DeleteGlobalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGlobalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalRequest) ProtoMessage() {}

func (x *DeleteGlobalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalRequest.ProtoReflect.Descriptor instead.
func (*DeleteGlobalRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteGlobalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SemagroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId    int32  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	SemaExpr string `protobuf:"bytes,2,opt,name=sema_expr,json=semaExpr,proto3" json:"sema_expr,omitempty"`
}

func (x *SemagroupRequest) Reset() {
	*x = SemagroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SemagroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemagroupRequest) ProtoMessage() {}

func (x *SemagroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemagroupRequest.ProtoReflect.Descriptor instead.
func (*SemagroupRequest) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{22}
}

func (x *SemagroupRequest) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *SemagroupRequest) GetSemaExpr() string {
	if x != nil {
		return x.SemaExpr
	}
	return ""
}

type SemagroupKeyValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SemagroupKeyValueResponse) Reset() {
	*x = SemagroupKeyValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SemagroupKeyValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemagroupKeyValueResponse) ProtoMessage() {}

func (x *SemagroupKeyValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemagroupKeyValueResponse.ProtoReflect.Descriptor instead.
func (*SemagroupKeyValueResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{23}
}

func (x *SemagroupKeyValueResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SemagroupKeyValueResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SemagroupDiffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SemagroupDiffResponse) Reset() {
	*x = SemagroupDiffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SemagroupDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemagroupDiffResponse) ProtoMessage() {}

func (x *SemagroupDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemagroupDiffResponse.ProtoReflect.Descriptor instead.
func (*SemagroupDiffResponse) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{24}
}

func (x *SemagroupDiffResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ListSemaphoresResponse_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value      int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Value0     int32                  `protobuf:"varint,3,opt,name=value0,proto3" json:"value0,omitempty"`
	Path       string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	IsLeaf     bool                   `protobuf:"varint,5,opt,name=is_leaf,json=isLeaf,proto3" json:"is_leaf,omitempty"`
	ChildCount int32                  `protobuf:"varint,6,opt,name=child_count,json=childCount,proto3" json:"child_count,omitempty"`
	Vtask      int64                  `protobuf:"varint,7,opt,name=vtask,proto3" json:"vtask,omitempty"`
	T          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=t,proto3" json:"t,omitempty"`
}

func (x *ListSemaphoresResponse_Node) Reset() {
	*x = ListSemaphoresResponse_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSemaphoresResponse_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSemaphoresResponse_Node) ProtoMessage() {}

func (x *ListSemaphoresResponse_Node) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSemaphoresResponse_Node.ProtoReflect.Descriptor instead.
func (*ListSemaphoresResponse_Node) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListSemaphoresResponse_Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListSemaphoresResponse_Node) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ListSemaphoresResponse_Node) GetValue0() int32 {
	if x != nil {
		return x.Value0
	}
	return 0
}

func (x *ListSemaphoresResponse_Node) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListSemaphoresResponse_Node) GetIsLeaf() bool {
	if x != nil {
		return x.IsLeaf
	}
	return false
}

func (x *ListSemaphoresResponse_Node) GetChildCount() int32 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

func (x *ListSemaphoresResponse_Node) GetVtask() int64 {
	if x != nil {
		return x.Vtask
	}
	return 0
}

func (x *ListSemaphoresResponse_Node) GetT() *timestamppb.Timestamp {
	if x != nil {
		return x.T
	}
	return nil
}

type ListVariablesResponse_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value      string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Path       string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	IsLeaf     bool                   `protobuf:"varint,4,opt,name=is_leaf,json=isLeaf,proto3" json:"is_leaf,omitempty"`
	ChildCount int32                  `protobuf:"varint,5,opt,name=child_count,json=childCount,proto3" json:"child_count,omitempty"`
	Vtask      int64                  `protobuf:"varint,6,opt,name=vtask,proto3" json:"vtask,omitempty"`
	T          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=t,proto3" json:"t,omitempty"`
}

func (x *ListVariablesResponse_Node) Reset() {
	*x = ListVariablesResponse_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coordination_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVariablesResponse_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariablesResponse_Node) ProtoMessage() {}

func (x *ListVariablesResponse_Node) ProtoReflect() protoreflect.Message {
	mi := &file_coordination_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariablesResponse_Node.ProtoReflect.Descriptor instead.
func (*ListVariablesResponse_Node) Descriptor() ([]byte, []int) {
	return file_coordination_proto_rawDescGZIP(), []int{12, 0}
}

func (x *ListVariablesResponse_Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListVariablesResponse_Node) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListVariablesResponse_Node) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListVariablesResponse_Node) GetIsLeaf() bool {
	if x != nil {
		return x.IsLeaf
	}
	return false
}

func (x *ListVariablesResponse_Node) GetChildCount() int32 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

func (x *ListVariablesResponse_Node) GetVtask() int64 {
	if x != nil {
		return x.Vtask
	}
	return 0
}

func (x *ListVariablesResponse_Node) GetT() *timestamppb.Timestamp {
	if x != nil {
		return x.T
	}
	return nil
}

var File_coordination_proto protoreflect.FileDescriptor

var file_coordination_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x58,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x30, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x30, 0x22, 0x63, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x66, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0xae, 0x02,
	0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62,
	0x6f, 0x78, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0xd6, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x30, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x30,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x65, 0x61, 0x66, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x74, 0x61, 0x73, 0x6b, 0x12, 0x28, 0x0a, 0x01, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x01, 0x74, 0x22, 0x82,
	0x01, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f,
	0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6d,
	0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x59, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x22, 0x43, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6d,
	0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x43, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3f,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x62, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x6f,
	0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x66, 0x4f,
	0x6e, 0x6c, 0x79, 0x22, 0x94, 0x02, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0xbe, 0x01, 0x0a, 0x04, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x68, 0x69,
	0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x74,
	0x61, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x74, 0x61, 0x73, 0x6b,
	0x12, 0x28, 0x0a, 0x01, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x01, 0x74, 0x22, 0x55, 0x0a, 0x12, 0x53, 0x65,
	0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x3f, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x42, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61,
	0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5c, 0x0a,
	0x08, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x28, 0x0a, 0x01, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x01, 0x74, 0x22, 0x43, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x4b,
	0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73,
	0x22, 0x3c, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x10, 0x53, 0x65, 0x6d,
	0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6d, 0x61, 0x5f, 0x65, 0x78, 0x70,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6d, 0x61, 0x45, 0x78, 0x70,
	0x72, 0x22, 0x45, 0x0a, 0x19, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4b, 0x65,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a, 0x15, 0x53, 0x65, 0x6d, 0x61,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xf7, 0x0b, 0x0a, 0x13, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x12,
	0x1d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6d,
	0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53,
	0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x73,
	0x12, 0x1f, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6d,
	0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f,
	0x78, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x62, 0x6f, 0x78, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68,
	0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x12, 0x20,
	0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6d,
	0x61, 0x70, 0x68, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f,
	0x78, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x4a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x1c, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x2e,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a,
	0x0a, 0x0b, 0x53, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x2e,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x12, 0x1a, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65,
	0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3f, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x1a,
	0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x45, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x12, 0x1d, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x52, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4b, 0x65, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x78,
	0x12, 0x1a, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6d, 0x61,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4f, 0x0a, 0x10, 0x44, 0x69, 0x66, 0x66, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78,
	0x2e, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6d,
	0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4f, 0x0a, 0x10, 0x44, 0x69, 0x66, 0x66, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x4d, 0x61, 0x78, 0x12, 0x1a, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f,
	0x78, 0x2e, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65,
	0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x12, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1a, 0x2e, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78,
	0x2e, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x12, 0x44, 0x65,
	0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x1a, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6d, 0x61,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6d, 0x61, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x22, 0x0a, 0x11, 0x6e, 0x65, 0x74, 0x2e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x62, 0x6f,
	0x78, 0x2e, 0x67, 0x70, 0x72, 0x63, 0x50, 0x01, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x62, 0x6f, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coordination_proto_rawDescOnce sync.Once
	file_coordination_proto_rawDescData = file_coordination_proto_rawDesc
)

func file_coordination_proto_rawDescGZIP() []byte {
	file_coordination_proto_rawDescOnce.Do(func() {
		file_coordination_proto_rawDescData = protoimpl.X.CompressGZIP(file_coordination_proto_rawDescData)
	})
	return file_coordination_proto_rawDescData
}

var file_coordination_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_coordination_proto_goTypes = []interface{}{
	(*GetSemaphoreRequest)(nil),         // 0: scalebox.GetSemaphoreRequest
	(*GetSemaphoreResponse)(nil),        // 1: scalebox.GetSemaphoreResponse
	(*ListSemaphoresRequest)(nil),       // 2: scalebox.ListSemaphoresRequest
	(*ListSemaphoresResponse)(nil),      // 3: scalebox.ListSemaphoresResponse
	(*CreateSemaphoreRequest)(nil),      // 4: scalebox.CreateSemaphoreRequest
	(*CreateSemaphoreResponse)(nil),     // 5: scalebox.CreateSemaphoreResponse
	(*UpdateSemaphoreRequest)(nil),      // 6: scalebox.UpdateSemaphoreRequest
	(*UpdateSemaphoreResponse)(nil),     // 7: scalebox.UpdateSemaphoreResponse
	(*DeleteSemaphoreRequest)(nil),      // 8: scalebox.DeleteSemaphoreRequest
	(*GetVariableRequest)(nil),          // 9: scalebox.GetVariableRequest
	(*GetVariableResponse)(nil),         // 10: scalebox.GetVariableResponse
	(*ListVariablesRequest)(nil),        // 11: scalebox.ListVariablesRequest
	(*ListVariablesResponse)(nil),       // 12: scalebox.ListVariablesResponse
	(*SetVariableRequest)(nil),          // 13: scalebox.SetVariableRequest
	(*SetVariableResponse)(nil),         // 14: scalebox.SetVariableResponse
	(*DeleteVariableRequest)(nil),       // 15: scalebox.DeleteVariableRequest
	(*GetGlobalRequest)(nil),            // 16: scalebox.GetGlobalRequest
	(*GetGlobalResponse)(nil),           // 17: scalebox.GetGlobalResponse
	(*KeyValue)(nil),                    // 18: scalebox.KeyValue
	(*ListGlobalsResponse)(nil),         // 19: scalebox.ListGlobalsResponse
	(*SetGlobalRequest)(nil),            // 20: scalebox.SetGlobalRequest
	(*DeleteGlobalRequest)(nil),         // 21: scalebox.DeleteGlobalRequest
	(*SemagroupRequest)(nil),            // 22: scalebox.SemagroupRequest
	(*SemagroupKeyValueResponse)(nil),   // 23: scalebox.SemagroupKeyValueResponse
	(*SemagroupDiffResponse)(nil),       // 24: scalebox.SemagroupDiffResponse
	(*ListSemaphoresResponse_Node)(nil), // 25: scalebox.ListSemaphoresResponse.Node
	(*ListVariablesResponse_Node)(nil),  // 26: scalebox.ListVariablesResponse.Node
	(*timestamppb.Timestamp)(nil),       // 27: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 28: google.protobuf.Empty
}
var file_coordination_proto_depIdxs = []int32{
	25, // 0: scalebox.ListSemaphoresResponse.nodes:type_name -> scalebox.ListSemaphoresResponse.Node
	26, // 1: scalebox.ListVariablesResponse.nodes:type_name -> scalebox.ListVariablesResponse.Node
	27, // 2: scalebox.KeyValue.t:type_name -> google.protobuf.Timestamp
	18, // 3: scalebox.ListGlobalsResponse.globals:type_name -> scalebox.KeyValue
	27, // 4: scalebox.ListSemaphoresResponse.Node.t:type_name -> google.protobuf.Timestamp
	27, // 5: scalebox.ListVariablesResponse.Node.t:type_name -> google.protobuf.Timestamp
	0,  // 6: scalebox.CoordinationService.GetSemaphore:input_type -> scalebox.GetSemaphoreRequest
	2,  // 7: scalebox.CoordinationService.ListSemaphores:input_type -> scalebox.ListSemaphoresRequest
	4,  // 8: scalebox.CoordinationService.CreateSemaphore:input_type -> scalebox.CreateSemaphoreRequest
	6,  // 9: scalebox.CoordinationService.UpdateSemaphore:input_type -> scalebox.UpdateSemaphoreRequest
	8,  // 10: scalebox.CoordinationService.DeleteSemaphore:input_type -> scalebox.DeleteSemaphoreRequest
	9,  // 11: scalebox.CoordinationService.GetVariable:input_type -> scalebox.GetVariableRequest
	11, // 12: scalebox.CoordinationService.ListVariables:input_type -> scalebox.ListVariablesRequest
	13, // 13: scalebox.CoordinationService.SetVariable:input_type -> scalebox.SetVariableRequest
	15, // 14: scalebox.CoordinationService.DeleteVariable:input_type -> scalebox.DeleteVariableRequest
	16, // 15: scalebox.CoordinationService.GetGlobal:input_type -> scalebox.GetGlobalRequest
	28, // 16: scalebox.CoordinationService.ListGlobals:input_type -> google.protobuf.Empty
	20, // 17: scalebox.CoordinationService.SetGlobal:input_type -> scalebox.SetGlobalRequest
	21, // 18: scalebox.CoordinationService.DeleteGlobal:input_type -> scalebox.DeleteGlobalRequest
	22, // 19: scalebox.CoordinationService.GetSemagroupMin:input_type -> scalebox.SemagroupRequest
	22, // 20: scalebox.CoordinationService.GetSemagroupMax:input_type -> scalebox.SemagroupRequest
	22, // 21: scalebox.CoordinationService.DiffSemagroupMin:input_type -> scalebox.SemagroupRequest
	22, // 22: scalebox.CoordinationService.DiffSemagroupMax:input_type -> scalebox.SemagroupRequest
	22, // 23: scalebox.CoordinationService.IncrementSemagroup:input_type -> scalebox.SemagroupRequest
	22, // 24: scalebox.CoordinationService.DecrementSemagroup:input_type -> scalebox.SemagroupRequest
	1,  // 25: scalebox.CoordinationService.GetSemaphore:output_type -> scalebox.GetSemaphoreResponse
	3,  // 26: scalebox.CoordinationService.ListSemaphores:output_type -> scalebox.ListSemaphoresResponse
	5,  // 27: scalebox.CoordinationService.CreateSemaphore:output_type -> scalebox.CreateSemaphoreResponse
	7,  // 28: scalebox.CoordinationService.UpdateSemaphore:output_type -> scalebox.UpdateSemaphoreResponse
	28, // 29: scalebox.CoordinationService.DeleteSemaphore:output_type -> google.protobuf.Empty
	10, // 30: scalebox.CoordinationService.GetVariable:output_type -> scalebox.GetVariableResponse
	12, // 31: scalebox.CoordinationService.ListVariables:output_type -> scalebox.ListVariablesResponse
	14, // 32: scalebox.CoordinationService.SetVariable:output_type -> scalebox.SetVariableResponse
	28, // 33: scalebox.CoordinationService.DeleteVariable:output_type -> google.protobuf.Empty
	17, // 34: scalebox.CoordinationService.GetGlobal:output_type -> scalebox.GetGlobalResponse
	19, // 35: scalebox.CoordinationService.ListGlobals:output_type -> scalebox.ListGlobalsResponse
	28, // 36: scalebox.CoordinationService.SetGlobal:output_type -> google.protobuf.Empty
	28, // 37: scalebox.CoordinationService.DeleteGlobal:output_type -> google.protobuf.Empty
	23, // 38: scalebox.CoordinationService.GetSemagroupMin:output_type -> scalebox.SemagroupKeyValueResponse
	23, // 39: scalebox.CoordinationService.GetSemagroupMax:output_type -> scalebox.SemagroupKeyValueResponse
	24, // 40: scalebox.CoordinationService.DiffSemagroupMin:output_type -> scalebox.SemagroupDiffResponse
	24, // 41: scalebox.CoordinationService.DiffSemagroupMax:output_type -> scalebox.SemagroupDiffResponse
	23, // 42: scalebox.CoordinationService.IncrementSemagroup:output_type -> scalebox.SemagroupKeyValueResponse
	23, // 43: scalebox.CoordinationService.DecrementSemagroup:output_type -> scalebox.SemagroupKeyValueResponse
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_coordination_proto_init() }
func file_coordination_proto_init() {
	if File_coordination_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coordination_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSemaphoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSemaphoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSemaphoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSemaphoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSemaphoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSemaphoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSemaphoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSemaphoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSemaphoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVariableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVariablesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVariablesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVariableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGlobalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGlobalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGlobalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetGlobalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGlobalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SemagroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SemagroupKeyValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SemagroupDiffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSemaphoresResponse_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coordination_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVariablesResponse_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coordination_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordination_proto_goTypes,
		DependencyIndexes: file_coordination_proto_depIdxs,
		MessageInfos:      file_coordination_proto_msgTypes,
	}.Build()
	File_coordination_proto = out.File
	file_coordination_proto_rawDesc = nil
	file_coordination_proto_goTypes = nil
	file_coordination_proto_depIdxs = nil
}
